apiVersion: v1
data:
  redis-password: eW91ci1yZWRpcy1wYXNzd29yZA==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-02T14:19:50Z"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.4.2
    helm.sh/chart: redis-20.10.0
  name: my-release-redis
  namespace: default
  resourceVersion: "24168"
  uid: 638b2b06-fa68-496b-8262-5bec4d360ee9
type: Opaque
